### ISSUE TITLE
Support `MagUnits`

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/asdf-astropy#145]
Support for `MagUnit` style units has been requested for the Roman Space Telescope output files. I think this is a reasonable request given we are working to resolve #144 (non-VOunits).

This should be relatively straight forward as we all `MagUnit` units essentially wrap a "physical unit" which we should be able to serialize already (for VOunits, and non-VOunits if #142 is merged). The heart of a schema for this would be:

```yaml
type: object
properties:
  unit:
     oneOf:
       - tag: "tag:stsci.edu:asdf/unit/unit-1.0.0"
       - tag: "tag:astropy.org:astropy/units/unit-1.0.0"
```

Once the schema is setup it should be relatively straightforward to get the `Converter` integrated and working.

@mhvk or @nstarman as `astropy.units` maintainers do I need to do anything besides wrapping the physical unit inside the `MagUnit`?
