### ISSUE TITLE
Access table metadata without loading data

### ISSUE THREAD

**Issue by LibrEars** [astropy/asdf-astropy#166]
Hello =)

Is it possible to access only the metadata of e.g. Qtables stored in the .asdf file-format without loading the data itself into memory? I tried to use `QTable.read()` with a `find_table ` key-word but `tree["data"]["meta"]` will result in an error since the meta-data alone does not represent a table.

In the [asdf documentation](https://asdf.readthedocs.io/en/latest/asdf/overview.html#reading-files) they state that "Array data remains unloaded until it is explicitly accessed". Therefore I thought it might be possible.

Here is a try using the example-data (QTable) from https://github.com/astropy/asdf-astropy/issues/118 :

```
# For the export of example data see issue 118
import asdf

# Is this only loading the meta-data into memory?
with asdf.open("Nr42_fluxgenerator.asdf") as af:
    meta = af["data"].meta

```

If this works, would it be useful to be implemented into astropy somehow?

**Comment by WilliamJamieson** [comment]
> Hello =)
> 
> Is it possible to access only the metadata of e.g. Qtables stored in the .asdf file-format without loading the data itself into memory? 

Yes and you correctly summarize this below:
> 
> In the [asdf documentation](https://asdf.readthedocs.io/en/latest/asdf/overview.html#reading-files) they state that "Array data remains unloaded until it is explicitly accessed". Therefore I thought it might be possible.
> 
> Here is a try using the example-data (QTable) from #118 :
> 
> ```python
> # For the export of example data see issue 118
> import asdf
> 
> # Is this only loading the meta-data into memory?
> with asdf.open("Nr42_fluxgenerator.asdf") as af:
>     meta = af["data"].meta
> ```
> 
This should enable you to read the metadata while lazy-loading the array data (assuming you aren't using some exotic file storage system).

> Or is a simple
> 
> ```python
> meta = QTable.read("Nr42_fluxgenerator.asdf").meta 
> ```
> 
> already doing the job without reading the table data into memory? Otherwise, would it be useful to be implemented into astropy somehow?

Without a much deeper investigation, I am not sure if this will also lazy-load the table's arrays when you need them. Just looking at the code in `asdf-astropy`, I think this should also lazy load the table meaning the arrays won't get loaded by this access, but it depends on if the `astropy` interface needs to actually access all the data passed to it or not.

@taldcroft do you know if this call https://github.com/astropy/asdf-astropy/blob/23131e63ad9f2bebd739c8db671edb4af2c2b49c/asdf_astropy/converters/table/table.py#L39-L45 will perform any accesses to the `data` passed in or not? If it does not actually access the data in the array itself, then the data in the array will remain on disk until one attempts to actually access values in it.

**Comment by perrygreenfield** [comment]
@LibrEars can you supply the yaml header of this file for us to inspect? (Or the whole file, but it may be too large to easily transport or have proprietary info you don't want to send). This can be done by using the command line utility `asdftool explode <filename>` which will split the file up into the YAML header and individual array files.

**Comment by LibrEars** [comment]
Thank you for your responses!

it is the same type of file as used for the example in https://github.com/astropy/asdf-astropy/issues/118 (you could use the code there to generate it. I can not upload to GitHub since .asdf is not supported for upload)


```
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.13.0}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.13.0}
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension._manifest.ManifestExtension
    extension_uri: asdf://astropy.org/astropy/extensions/astropy-1.0.0
    software: !core/software-1.0.0 {name: asdf-astropy, version: 0.2.2}
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension._manifest.ManifestExtension
    extension_uri: asdf://asdf-format.org/core/extensions/core-1.5.0
    software: !core/software-1.0.0 {name: asdf-astropy, version: 0.2.2}
data: !<tag:astropy.org:astropy/table/table-1.0.0>
  colnames: [Curren, Fluxgenerated_flux]
  columns:
  - !unit/quantity-1.1.0
    unit: !unit/unit-1.0.0 A
    value: !core/ndarray-1.0.0
      source: 0
      datatype: float64
      byteorder: little
      shape: [20]
  - !unit/quantity-1.1.0
    unit: !unit/unit-1.0.0 flx
    value: !core/ndarray-1.0.0
      source: 1
      datatype: float64
      byteorder: little
      shape: [20]
  meta: {Experimentalist: LibrEars, measurement_type: flux_of_fluxgenerator, nr: 42,
    pix: 7, temperature: 37, time: 'Wed Oct  5 09:59:08 2022', voltage: -2}
  qtable: true
...
```
